url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: "Mart Dingley | Web Developer"

plugins:
  - jekyll-postcss

sass:
  sourcemap: never

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
  - public
  # - assets/css/tailwind.scss

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/